### ISSUE TITLE
Transcription File Explanation

### ISSUE THREAD

**Issue by tulasiram58827** [Speech-Lab-IITM/English_ASR_Challenge#1]
I just downloaded the data and going through it. But I am having some confusions regarding transcriptions file
```
ahd_301_long_1010_eng-000000-003000-1-1 [NOISE] YOUTUBE NOW SUPPORTS HIGH DYNAMIC RANGE VIDEOS H
ahd_301_long_1010_eng-000000-003000-2-1 !SIL VIDEOS HAVEHIGHER CONTRAST REVEALING PRECISE DETAILED SHADOWS AND STUNNING HIGHLIGHTS WITH !SIL
ahd_301_long_1010_eng-000000-003000-2-2 !SIL MORE CLARITY THAN EVER
ahd_301_long_1010_eng-000000-003000-3-1 SAID STEVEN ROBERTSON
ahd_301_long_1010_eng-000000-003000-4-1 SOFTWARE ENGINEER
ahd_301_long_1010_eng-000000-003000-5-1 AND SANJEEV VERMA PRODUCT MANAGER IN A BLOGPOST STARTING TODAY USERS
```

Can you give a bit more explanation of transcription files. I can see multiple lines of transcription for each audio file

@yttehs

**Comment by yttehs** [comment]
Hi Tulasiram,

The audio files that we have shared are more than a minute long in case of IITM data and about 40 minutes long in case of NPTEL data. Ideally, to train an ASR model, it is suggested to have files around 10-15 seconds long. In order to deal with such "long utterances" what we have done is that, the utterances are split into smaller segments with manageable(5 sec - 15 sec) length. That is the reason why you can see multiple entries in the "text" file for the same utterance. Basically each entry is the smaller chunk of the big audio file. You can observe that each of these utterances from the same audio file have a unique suffix to distinguish them from each other. The exact timing information for a given utterance is given in the "segments" file. 

The format of the "text" file is as follows:
<audio_1_utt_id_1>   <Corresponding text 1>
<audio_1_utt_id_2>   <Corresponding text 2>
<audio_1_utt_id_3>   <Corresponding text 3>

and that for the "segments" file is as follows:
<audio_1_utt_id_1>  <audio_1_name> start_time_1   end_time_1  
<audio_1_utt_id_2>  <audio_1_name> start_time_2   end_time_2
<audio_1_utt_id_3>  <audio_1_name> start_time_3   end_time_3   

How to interpret it?
In the above example, there is one audio file named <audio_1_name>, which is split into three smaller segments <audio_1_utt_id_1>, <audio_1_utt_id_2> and <audio_1_utt_id_3>.  
<audio_1_utt_id_1> lies between "start_time_1"  and "end_time_1" in the file <audio_1_name>
<audio_1_utt_id_2> lies between "start_time_2"  and "end_time_2" in the file <audio_1_name>
<audio_1_utt_id_3> lies between "start_time_3"  and "end_time_3" in the file <audio_1_name>

**Comment by tulasiram58827** [comment]
Thank you so much @yttehs for the clear explanation.

**Comment by yunxinmengze** [comment]
@tulasiram58827 
The data download channel has been closed. Can you share the downloaded data.
thank you very mush.

**Comment by yunxinmengze** [comment]
@yttehs 
The data download channel has been closed. Can you share the downloaded data.
thank you very mush.

**Comment by yttehs** [comment]
@adithyarajk 
Please can you help @yunxinmengze with the data?

**Comment by yunxinmengze** [comment]
@yttehs 
Hello, is there any other way I can get this data?

**Comment by yunxinmengze** [comment]
&nbsp;


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Hello,I am sorry to send you this email.I alse applied for these datasets recently fill this form in their website.Unfortunately,the tunnels are closed.&nbsp;But the datasets of indian english in particular demend these days.You can provide training sets or dev sets .If you feel like the data set is big . It would be appreciated if you can provide lexicion.txt and phone.txt.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Looking forward to you reply,be deeply grateful.




&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; yunxin mengze





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Speech-Lab-IITM/English_ASR_Challenge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月23日(星期四) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Speech-Lab-IITM/English_ASR_Challenge] Transcription File Explanation (#1)





 
@adithyarajk
 Please can you help @yunxinmengze with the data?

**Comment by yunxinmengze** [comment]
@yttehs This data set is urgently needed,I can pay for it.Looking forward to your relpay

**Comment by yunxinmengze** [comment]
@redleaf-lite  this is my email  948307442@qq.com,Can you send me a message through this.I have no ability to use the link with you gave me.
